### ISSUE TITLE
Receiving a panic runtime error when attempting to renew after expiration

### ISSUE THREAD

**Issue by webash** [xenolf/lego#191]
```
user@machine:~/utils/lego$ sudo ./lego --domains="<existing domain>" --email="<existing email address>" renew
2016/04/14 17:23:15 [INFO][<existing domain>] acme: Trying renewal with -42 hours remaining
2016/04/14 17:23:15 [INFO][<existing domain>] acme: Obtaining bundled SAN certificate
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a45e9]

goroutine 16 [running]:
panic(0x95f440, 0xc8200100e0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc820102090, 0xc82023acc0, 0xc82023ac60, 0xc8203f53a0, 0x14)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:408 +0x5c9
created by github.com/xenolf/lego/acme.(*Client).getChallenges
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:421 +0x17c
```

If there's any other info I need to provide, please let me know!

**Comment by xenolf** [comment]
Hey! I'm not entirely sure what could possibly be nil here :smile: 
Could you check the file at `.lego/accounts/<acme-server-url>/<your@email.com>/account.json` if the registration property is filled out?

**Comment by webash** [comment]
Yup seems to be! I omitted a bunch of info here (as it seems important! ha!)... but otherwise seems fully populated.

```
{
        "email": "<omitted>",
        "registration": {
                "body": {
                        "resource": "reg",
                        "id": <omitted>,
                        "key": {
                                "kty": "RSA",
                                "n": "<omitted>",
                                "e": "<omitted>"
                        },
                        "contact": [
                                "mailto:<omitted>"
                        ],
                        "agreement": "https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf"
                },
                "uri": "https://acme-v01.api.letsencrypt.org/acme/reg/230065",
                "new_authzr_uri": "https://acme-v01.api.letsencrypt.org/acme/new-authz",
                "terms_of_service": "https://letsencrypt.org/documents/LE-SA-v1.0.1-July-27-2015.pdf"
        }
}
```

**Comment by xenolf** [comment]
Just to be sure, which version of the CLI are you using?

**Comment by webash** [comment]
I was previously using 0.2.0. I got the error then, so decided I should upgrade to 0.3.0 by dumping the new version over top - but I still receive the error.

**Comment by xenolf** [comment]
Is the stacktrace any different when using v0.3.0?

**Comment by webash** [comment]
The above stack trace was from v0.3.0. This was the trace from v0.2.0:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a10df]

goroutine 13 [running]:
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc8203a4780, 0xc82038f2c0, 0xc82038f260, 0xc8203c1520, 0x14)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:386 +0x5bf
created by github.com/xenolf/lego/acme.(*Client).getChallenges
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:399 +0x187

goroutine 1 [select]:
github.com/xenolf/lego/acme.(*Client).getChallenges(0xc8203a4780, 0xc8203ea758, 0x1, 0x1, 0x0, 0x0, 0x0, 0x1)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:405 +0x6e8
github.com/xenolf/lego/acme.(*Client).ObtainCertificate(0xc8203a4780, 0xc8203ea758, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:211 +0x1c0
github.com/xenolf/lego/acme.(*Client).RenewCertificate(0xc8203a4780, 0xc8203c1520, 0x14, 0xc82038ef00, 0x53, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:330 +0xf77
main.renew(0xc820068d80)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/cli_handlers.go:238 +0x18fb
github.com/codegangsta/cli.Command.Run(0x8340c0, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x870a30, 0x13, 0x0, ...)
        /home/azhwkd/Projects/go/src/github.com/codegangsta/cli/command.go:137 +0x107e
github.com/codegangsta/cli.(*App).Run(0xc820068b40, 0xc82000a140, 0x4, 0x4, 0x0, 0x0)
        /home/azhwkd/Projects/go/src/github.com/codegangsta/cli/app.go:175 +0xfff
main.main()
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/cli.go:113 +0xfab

goroutine 11 [IO wait]:
net.runtime_pollWait(0x7fed109aba68, 0x72, 0xc8200101a0)
        /usr/local/go/src/runtime/netpoll.go:157 +0x60
net.(*pollDesc).Wait(0xc8200b3330, 0x72, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8200b3330, 0x0, 0x0)
        /usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8200b32d0, 0xc8200e4000, 0x2000, 0x2000, 0x0, 0x7fed109a6050, 0xc8200101a0)
        /usr/local/go/src/net/fd_unix.go:232 +0x23a
net.(*conn).Read(0xc820026090, 0xc8200e4000, 0x2000, 0x2000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8200d65d0, 0x7fed109abec8, 0xc820026090, 0x5, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:455 +0xcc
crypto/tls.(*Conn).readRecord(0xc820084840, 0x8e1517, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:540 +0x2d1
crypto/tls.(*Conn).Read(0xc820084840, 0xc8200e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/crypto/tls/conn.go:901 +0x167
net/http.noteEOFReader.Read(0x7fed109b4a18, 0xc820084840, 0xc82009a738, 0xc8200e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        /usr/local/go/src/net/http/transport.go:1370 +0x67
net/http.(*noteEOFReader).Read(0xc8203c12a0, 0xc8200e3000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
        <autogenerated>:126 +0xd0
bufio.(*Reader).fill(0xc82038ed20)
        /usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc82038ed20, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc82009a6e0)
        /usr/local/go/src/net/http/transport.go:876 +0xf7
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:685 +0xc78

goroutine 12 [select]:
net/http.(*persistConn).writeLoop(0xc82009a6e0)
        /usr/local/go/src/net/http/transport.go:1009 +0x40c
created by net/http.(*Transport).dialConn
        /usr/local/go/src/net/http/transport.go:686 +0xc9d

```

Which seems weird as it has net/http problems that v0.3.0 doesn't?

**Comment by xenolf** [comment]
> Which seems weird as it has net/http problems that v0.3.0 doesn't?

That's just because 0.2.0 used to dump all go routines on panic... 0.3.0 doesn't do that anymore.

I'm trying to reproduce this localy, but so far havn't been successful :worried:

**Comment by xenolf** [comment]
What OS are you running this on? I'd like to give you a binary with some logging just before the failing line to see what's nil.

You can of course also do this yourself if you have go installed. The logging would need to be just before line 408 in `client.go`. Just log the value of any variable on line 408.

**Comment by webash** [comment]
Woops sorry, haven't configured email alerts for comments and didn't check for an update!

I'm running it on Ubuntu 14.04.4 LT x64 in an Azure VM. I don't have go installed and would prefer not to on this particular machine, so are you able to fire the modified binary my way?

**Comment by xenolf** [comment]
Sure :)

Here you go: 
[lego.zip](https://github.com/xenolf/lego/files/225050/lego.zip)

**Comment by webash** [comment]
Thanks! Here's the output. I'm not sure what stuff is sensitive so I've done my best not to obscure too much without giving too much away:

```
2016/04/19 14:30:53 [INFO][<domain>] acme: Trying renewal with -159 hours remaining
2016/04/19 14:30:53 [INFO][<domain>] acme: Obtaining bundled SAN certificate
2016/04/19 14:30:53 [DEBUG] JWS: &{https://acme-v01.api.letsencrypt.org/directory %!s(*rsa.PrivateKey=&{{0x<hex-start>920 65537} 0x<hex-start>940 [0x<hex-start>960 0x<hex-start>980] {0x<hex-start>a20 0x<hex-start>a40 0x<hex-start>a60 []}}) []}, User: &{<email> 0xc82004e840 <nil> 0xc820020078}, Reg: <nil>, AuthMsg: {new-authz {dns <domain>}  0001-01-01 00:00:00 +0000 UTC [] []}
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x4a5c2d]

goroutine 16 [running]:
panic(0xa5aac0, 0xc8200100f0)
        /usr/local/go/src/runtime/panic.go:464 +0x3e6
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc82010a090, 0xc820238c60, 0xc820238c00, 0xc8203fb380, 0x14)
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:409 +0x80d
created by github.com/xenolf/lego/acme.(*Client).getChallenges
        /home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:422 +0x17c
```

**Comment by xenolf** [comment]
So the offending part seems to be the registration altho the file you posted above looks perfectly fine.
I was able to encounter the exact same stack trace by forging an `account.json` with a `registration` property which was named wrong. Could you please double check that it really loads the right `account.json` and if the content is valid JSON?

**Comment by webash** [comment]
How could I be sure it's loading the right account.json? I'll extract the file and ensure all the line endings are consistent etc, but the dump I provided above looks fine.

**Comment by webash** [comment]
the JSON file is valid :(

**Comment by webash** [comment]
Ok plot thickens... 

Having had the server's FS open in an SFTP client I could properly see the folder hierarchy and noticed the following:
.lego/
--accounts/
----<acme-url>/
------<email>
--------./keys/
----------<email>.key
.lego/
--<acme-url>/
----<email>/
------account.json
------keys/
--------<email>.key

I assume only one of those is right?

**Comment by webash** [comment]
Ugh... moving the data to the ./lego/accounts/ instead of sitting straight in .lego/ works - I successfully have my new cert now...

**Comment by xenolf** [comment]
Ugh... I wonder how it ended up there? Did you use a like early early early version of lego back last year?

**Comment by webash** [comment]
Nope not as far as I know. Maybe I butchered my backup folder copy at some point... but when I first ran the renew command and received the error from 0.2.0 it would've been exactly as I left it after I first got my cert.

**Comment by xenolf** [comment]
Well. I will make sure that the renew command displays an error if it was unable to load the file properly.

**Comment by webash** [comment]
Ok great. Thanks for your help... I'm really unsure how this happened. Feel free to close this issue :)
