### ISSUE TITLE
panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by fit-fg** [xenolf/lego#384]
When using the Let's encrypt staging API to issue a SAN for 4 domains a `slice bounds out of range` runtime panic occurred. I was not able to reproduce it.

```
2017/04/25 10:15:36 [INFO] acme: Registering account for development@######.com
2017/04/25 10:15:36 [INFO][inserter-staging.#####.com, inserter-staging2.#####.com, inserter-staging3.#####.com, inserter-staging4.#####.com] acme: Obtaining SAN certificate
panic: runtime error: slice bounds out of range

goroutine 123 [running]:
panic(0x1398600, 0xc420014160)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/xenolf/lego/acme.(*jws).Nonce(0xc4203863c0, 0x0, 0x0, 0x0, 0x0)
        /home/fabian/work/src/github.com/xenolf/lego/acme/jws.go:113 +0x1bf
gopkg.in/square/go-jose%2ev1.(*genericSigner).Sign(0xc4202de1b0, 0xc4209840b0, 0x82, 0xa2, 0x7f3a948fa8c8, 0xc4202de1b0, 0x0)
        /home/fabian/work/src/gopkg.in/square/go-jose.v1/signing.go:158 +0x64f
github.com/xenolf/lego/acme.(*jws).signContent(0xc4203863c0, 0xc4209840b0, 0x82, 0xa2, 0xc4208443f0, 0x99, 0x100)
        /home/fabian/work/src/github.com/xenolf/lego/acme/jws.go:72 +0x100
github.com/xenolf/lego/acme.(*jws).post(0xc4203863c0, 0xc4201c4230, 0x37, 0xc4209840b0, 0x82, 0xa2, 0x0, 0x88, 0x88)
        /home/fabian/work/src/github.com/xenolf/lego/acme/jws.go:37 +0x67
github.com/xenolf/lego/acme.postJSON(0xc4203863c0, 0xc4201c4230, 0x37, 0x1452240, 0xc4208443f0, 0x12dc500, 0xc420844360, 0x0, 0x0, 0x0)
        /home/fabian/work/src/github.com/xenolf/lego/acme/http.go:96 +0x153
github.com/xenolf/lego/acme.(*Client).getChallenges.func1(0xc4205aa120, 0xc4205ac120, 0xc4205ac0c0, 0xc4203d7320, 0x22)
        /home/fabian/work/src/github.com/xenolf/lego/acme/client.go:526 +0x1c6
created by github.com/xenolf/lego/acme.(*Client).getChallenges
        /home/fabian/work/src/github.com/xenolf/lego/acme/client.go:539 +0x113
```

Using lego acme client like this:
```go
package main

import (
	"crypto"
	"crypto/rand"
	"crypto/rsa"
	"log"

	"github.com/xenolf/lego/acme"
	"github.com/xenolf/lego/providers/dns/cloudflare"
)

// You'll need a user or account type that implements acme.User
type user struct {
	Email        string
	Registration *acme.RegistrationResource
	key          crypto.PrivateKey
}

func (u user) GetEmail() string {
	return u.Email
}
func (u user) GetRegistration() *acme.RegistrationResource {
	return u.Registration
}
func (u user) GetPrivateKey() crypto.PrivateKey {
	return u.key
}

func renewCert(hosts []string) acme.CertificateResource {
	// Create a user. New accounts need an email and private key to start.
	const rsaKeySize = 2048
	privateKey, err := rsa.GenerateKey(rand.Reader, rsaKeySize)
	if err != nil {
		log.Fatal(err)
	}
	user := user{
		Email: "development@#####.com",
		key:   privateKey,
	}

	// A client facilitates communication with the CA server.
	var url string
	if *dry {
		url = "https://acme-staging.api.letsencrypt.org/directory"
	} else {
		url = "https://acme-v01.api.letsencrypt.org/directory"
	}
	client, err := acme.NewClient(url, &user, acme.RSA2048)
	if err != nil {
		log.Fatal(err)
	}

	// New users will need to register
	reg, err := client.Register()
	if err != nil {
		log.Fatal(err)
	}
	user.Registration = reg

	// Set the DNS provider.
	provider, err := cloudflare.NewDNSProvider()
	if err != nil {
		log.Fatal(err)
	}
	client.SetChallengeProvider(acme.DNS01, provider)

	// Exclude all other challenges.
	client.ExcludeChallenges([]acme.Challenge{acme.HTTP01, acme.TLSSNI01})

	// The client has a URL to the current Let's Encrypt Subscriber
	// Agreement. The user will need to agree to it.
	err = client.AgreeToTOS()
	if err != nil {
		log.Fatal(err)
	}
	// The acme library takes care of completing the challenges to obtain the certificate(s).
	// The domains must resolve to this machine or you have to use the DNS challenge.
	c, failures := client.ObtainCertificate(hosts, false, nil, false)
	if len(failures) > 0 {
		log.Fatal(failures)
	}
	return c
}
```

**Comment by xenolf** [comment]
What version of lego did you use? The line numbers do not match that of current master.

**Comment by ldez** [comment]
I close due to inactivity and age.
