### ISSUE TITLE
v0.3.1 release doesn't work on macOS Sierra

### ISSUE THREAD

**Issue by sirnacnud** [xenolf/lego#406]
The v0.3.1 release crashes on macOS Serria (10.12.5) with the below stack trace. I believe it is related to a memory issue with the version of Go that is bundled with this release and macOS Sierra.
```
failed MSpanList_Insert 0xc0f3d8 0x1716d0823495 0x0 0x0
fatal error: MSpanList_Insert

runtime stack:
runtime.throw(0x79b320, 0x10)
	/usr/local/go/src/runtime/panic.go:530 +0x90
runtime.(*mSpanList).insert(0xa931c8, 0xc0f3d8)
	/usr/local/go/src/runtime/mheap.go:933 +0x293
runtime.(*mheap).freeSpanLocked(0xa929c0, 0xc0f3d8, 0x100, 0x0)
	/usr/local/go/src/runtime/mheap.go:809 +0x4be
runtime.(*mheap).grow(0xa929c0, 0x8, 0x0)
	/usr/local/go/src/runtime/mheap.go:675 +0x2a0
runtime.(*mheap).allocSpanLocked(0xa929c0, 0x1, 0xb7df48)
	/usr/local/go/src/runtime/mheap.go:553 +0x4e3
runtime.(*mheap).alloc_m(0xa929c0, 0x1, 0x1e, 0xb7df48)
	/usr/local/go/src/runtime/mheap.go:437 +0x119
runtime.(*mheap).alloc.func1()
	/usr/local/go/src/runtime/mheap.go:502 +0x41
runtime.systemstack(0xc82003de58)
	/usr/local/go/src/runtime/asm_amd64.s:307 +0xab
runtime.(*mheap).alloc(0xa929c0, 0x1, 0x1000000001e, 0x1f4ef)
	/usr/local/go/src/runtime/mheap.go:503 +0x63
runtime.(*mcentral).grow(0xa949b0, 0x0)
	/usr/local/go/src/runtime/mcentral.go:209 +0x93
runtime.(*mcentral).cacheSpan(0xa949b0, 0xb7ae88)
	/usr/local/go/src/runtime/mcentral.go:89 +0x47d
runtime.(*mcache).refill(0xb76000, 0x1e, 0xb7ae88)
	/usr/local/go/src/runtime/mcache.go:119 +0xcc
runtime.mallocgc.func2()
	/usr/local/go/src/runtime/malloc.go:642 +0x2b
runtime.systemstack(0xc82001b500)
	/usr/local/go/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/usr/local/go/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/usr/local/go/src/runtime/asm_amd64.s:245 fp=0xc8203b17b8 sp=0xc8203b17b0
runtime.mallocgc(0x380, 0x0, 0x3, 0x0)
	/usr/local/go/src/runtime/malloc.go:643 +0x869 fp=0xc8203b1890 sp=0xc8203b17b8
runtime.rawstring(0x338, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:284 +0x70 fp=0xc8203b18d8 sp=0xc8203b1890
runtime.rawstringtmp(0x0, 0x338, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:111 +0xb7 fp=0xc8203b1910 sp=0xc8203b18d8
runtime.slicebytetostring(0x0, 0xc820074700, 0x338, 0x338, 0x0, 0x0)
	/usr/local/go/src/runtime/string.go:93 +0x6f fp=0xc8203b19a8 sp=0xc8203b1910
encoding/base64.(*Encoding).EncodeToString(0xc82008a160, 0xc820418000, 0x268, 0x499, 0x0, 0x0)
	/usr/local/go/src/encoding/base64/base64.go:144 +0x10e fp=0xc8203b1a00 sp=0xc8203b19a8
github.com/xenolf/lego/acme.(*Client).requestCertificate(0xc82009c480, 0xc8203660c0, 0x1, 0x1, 0x1, 0x6bdda0, 0xc8202ac060, 0x0, 0x0, 0x0, ...)
	/home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:475 +0x5c9 fp=0xc8203b20a0 sp=0xc8203b1a00
github.com/xenolf/lego/acme.(*Client).ObtainCertificate(0xc82009c480, 0xc82050ec90, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:233 +0x45a fp=0xc8203b2488 sp=0xc8203b20a0
github.com/xenolf/lego/acme.(*Client).RenewCertificate(0xc82009c480, 0xc8200f26e0, 0x14, 0xc820068480, 0x53, 0x0, 0x0, 0xc8203a2980, 0x35, 0x0, ...)
	/home/azhwkd/Projects/go/src/github.com/xenolf/lego/acme/client.go:352 +0x1114 fp=0xc8203b2838 sp=0xc8203b2488
main.renew(0xc8200f7200)
	/home/azhwkd/Projects/go/src/github.com/xenolf/lego/cli_handlers.go:327 +0x191c fp=0xc8203b2db0 sp=0xc8203b2838
github.com/codegangsta/cli.Command.Run(0x737588, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x79bce0, 0x13, 0x0, ...)
	/home/azhwkd/Projects/go/src/github.com/codegangsta/cli/command.go:137 +0x1081 fp=0xc8203b3348 sp=0xc8203b2db0
github.com/codegangsta/cli.(*App).Run(0xc8200f6fc0, 0xc820068060, 0x6, 0x6, 0x0, 0x0)
	/home/azhwkd/Projects/go/src/github.com/codegangsta/cli/app.go:175 +0xffa fp=0xc8203b39d8 sp=0xc8203b3348
main.main()
	/home/azhwkd/Projects/go/src/github.com/xenolf/lego/cli.go:144 +0x14da fp=0xc8203b3f30 sp=0xc8203b39d8
runtime.main()
	/usr/local/go/src/runtime/proc.go:188 +0x2b0 fp=0xc8203b3f80 sp=0xc8203b3f30
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8203b3f88 sp=0xc8203b3f80

goroutine 4 [IO wait]:
net.runtime_pollWait(0xda7000, 0x72, 0xc8201f4800)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203e8220, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203e8220, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203e81c0, 0xc8201f4800, 0x800, 0x800, 0x0, 0xc06028, 0xc82006a0b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc8203cc038, 0xc8201f4800, 0x800, 0x800, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8203be870, 0xda72a0, 0xc8203cc038, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc8203f4000, 0x85f017, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc8203f4000, 0xc8203f7000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xbcaa98, 0xc8203f4000, 0xc8203c6068, 0xc8203f7000, 0x1000, 0x1000, 0x15a13, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc8205922c0, 0xc8203f7000, 0x1000, 0x1000, 0xc8204e5d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc8203a04e0)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc8203a04e0, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc8203c6000)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 5 [select]:
net/http.(*persistConn).writeLoop(0xc8203c6000)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb

goroutine 65 [IO wait]:
net.runtime_pollWait(0xda6e80, 0x72, 0xc8204a4000)
	/usr/local/go/src/runtime/netpoll.go:160 +0x60
net.(*pollDesc).Wait(0xc8203e9170, 0x72, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:73 +0x3a
net.(*pollDesc).WaitRead(0xc8203e9170, 0x0, 0x0)
	/usr/local/go/src/net/fd_poll_runtime.go:78 +0x36
net.(*netFD).Read(0xc8203e9110, 0xc8204a4000, 0x1000, 0x1000, 0x0, 0xc06028, 0xc82006a0b0)
	/usr/local/go/src/net/fd_unix.go:250 +0x23a
net.(*conn).Read(0xc82008e088, 0xc8204a4000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/net.go:172 +0xe4
crypto/tls.(*block).readFromUntil(0xc8203a78f0, 0xda72a0, 0xc82008e088, 0x5, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:460 +0xcc
crypto/tls.(*Conn).readRecord(0xc820446000, 0x85f017, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:562 +0x2d1
crypto/tls.(*Conn).Read(0xc820446000, 0xc8204a5000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/go/src/crypto/tls/conn.go:939 +0x167
net/http.noteEOFReader.Read(0xbcaa98, 0xc820446000, 0xc820070e38, 0xc8204a5000, 0x1000, 0x1000, 0x15a13, 0x0, 0x0)
	/usr/local/go/src/net/http/transport.go:1683 +0x67
net/http.(*noteEOFReader).Read(0xc82036ed00, 0xc8204a5000, 0x1000, 0x1000, 0xc820509d0d, 0x0, 0x0)
	<autogenerated>:284 +0xd0
bufio.(*Reader).fill(0xc820365860)
	/usr/local/go/src/bufio/bufio.go:97 +0x1e9
bufio.(*Reader).Peek(0xc820365860, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/bufio/bufio.go:132 +0xcc
net/http.(*persistConn).readLoop(0xc820070dd0)
	/usr/local/go/src/net/http/transport.go:1069 +0x177
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:853 +0x10a6

goroutine 66 [select]:
net/http.(*persistConn).writeLoop(0xc820070dd0)
	/usr/local/go/src/net/http/transport.go:1273 +0x472
created by net/http.(*Transport).dialConn
	/usr/local/go/src/net/http/transport.go:854 +0x10cb
```

**Comment by xenolf** [comment]
This should be fixed with the latest release.
