### ISSUE TITLE
FastDNS: Do not overwrite existing TXT records

### ISSUE THREAD

**Issue by securez** [xenolf/lego#763]
When requesting a certificate for `*.mydomian.com` and `mydomain.com` using dns-01 challenge, and FastDNS provider, the TXT gets overridden and the TXT verify fail most of the times with this error:

```
[*.mydomain.com] time limit exceeded: last error: NS a1-216.akam.net. did not return the expected TXT record...
```
Version: lego version 2.0.1 linux/amd64 

The command that i use:
```bash
lego -s https://acme-staging-v02.api.letsencrypt.org/directory -a --email myemail@email.com --dns fastdns --pem --dns.resolvers a1-216.akam.net -d 'mydomain.com' -d '*.mydomain.com' run
```

This seems the same issue resolved for Azure in https://github.com/xenolf/lego/pull/726. The error is not about timeout, i raise it for the test with no success, is because one of the challenges overrides the other, and one of then never completes.

If i have some time, i'll try to investigate how to solve the issue, this error seems probable to appear in other providers, I'll think in a solution that will help to all providers. The thing thar are around my brain is to clear TXT records, before creating the new ones for the challenge, and of course no override existing TXT records for the same name. This will happen always forn SAN and Wildcard certificate at same time.

NOTE: I changed domain name and emails for safety.

**Comment by ldez** [comment]
@securez Could you give the exact lego version that you use?

The issue seems similar to #726 but the [FastDNS API](https://developer.akamai.com/api/web_performance/fast_dns_record_management/v1.html#recordmanagement) seems to allow to have several entries for the same domain.

**Comment by securez** [comment]
Hi, Sorry I missed it, I edited the original post. I didn't have much time to get deeper, but when I request the domains one by one all is working as expected, but when wildcard and san is mixed, from that i read on the code multiple TXT records needs to be created, but in these lines: https://github.com/xenolf/lego/blob/master/providers/dns/fastdns/fastdns.go#L92-L103 seems that records with the same name are deleted prior to create the new one, L98. When the request fails, and I make a TXT request to DNS server, only one record is present.

**Comment by securez** [comment]
Hi @ldez not problem at all, I can build the binary, and make some test with real domain, but I can't test it until Thursday.

**Comment by ldez** [comment]
great :+1: I will prepare some branches tomorrow.

**Comment by ldez** [comment]
@securez could you try with with this branch [fix/fastdns](https://github.com/xenolf/lego/tree/fix/fastdns)

**Comment by securez** [comment]
Hi @ldez,

I compiled the fix/fastdns branch, and launch the same wildcard plus san test, now the challenge seems to complete ok, but other error is happening.

Command used in the test, I replaced domain names and emails.

```bash
AKAMAI_HOST=akab-*******.luna.akamaiapis.net AKAMAI_CLIENT_TOKEN=****** AKAMAI_CLIENT_SECRET=****** AKAMAI_ACCESS_TOKEN=****** AKAMAI_PROPAGATION_TIMEOUT=300 AKAMAI_POLLING_INTERVAL=5 AKAMAI_TTL=120 ./lego -s https://acme-staging-v02.api.letsencrypt.org/directory -a --email myemail@email.com --dns fastdns --pem --dns.resolvers a1-216.akam.net -d 'sub.mycomain.com' -d '*.sub.mycomain.com' run
2019/01/23 11:49:31 No key found for account myemail@email.com. Generating a curve P384 EC key.
2019/01/23 11:49:31 Saved key to /home/vagrant/.lego/accounts/acme-staging-v02.api.letsencrypt.org/myemail@email.com/keys/myemail@email.com.key
2019/01/23 11:49:32 [INFO] acme: Registering account for myemail@email.com
!!!! HEADS UP !!!!

		Your account credentials have been saved in your Let's Encrypt
		configuration directory at "/home/vagrant/.lego/accounts".
		You should make a secure backup	of this folder now. This
		configuration directory will also contain certificates and
		private keys obtained from Let's Encrypt so making regular
		backups of this folder is ideal.2019/01/23 11:49:33 [INFO] [sub.mycomain.com, *.sub.mycomain.com] acme: Obtaining bundled SAN certificate
2019/01/23 11:49:34 [INFO] [*.sub.mycomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/OLM03rbIyqvTR55sVbbIZ8BYoIfGqp3-Yo1w_gocyao
2019/01/23 11:49:34 [INFO] [sub.mycomain.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz/6JR_DXDWcHCTL6vs34P4LtYm_FOGGw86xOLJ76wswPU
2019/01/23 11:49:34 [INFO] [*.sub.mycomain.com] acme: use dns-01 solver
2019/01/23 11:49:34 [INFO] [sub.mycomain.com] acme: Could not find solver for: tls-alpn-01
2019/01/23 11:49:34 [INFO] [sub.mycomain.com] acme: Could not find solver for: http-01
2019/01/23 11:49:34 [INFO] [sub.mycomain.com] acme: use dns-01 solver
2019/01/23 11:49:34 [INFO] [*.sub.mycomain.com] acme: Preparing to solve DNS-01
2019/01/23 11:49:39 [INFO] [sub.mycomain.com] acme: Preparing to solve DNS-01
2019/01/23 11:49:40 [INFO] [*.sub.mycomain.com] acme: Trying to solve DNS-01
2019/01/23 11:49:40 [INFO] [*.sub.mycomain.com] acme: Checking DNS record propagation using [a1-216.akam.net:53]
2019/01/23 11:49:40 [INFO] Wait for propagation [timeout: 5m0s, interval: 5s]
2019/01/23 11:49:42 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:49:47 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:49:53 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:49:59 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:04 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:10 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:16 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:21 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:27 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:33 [INFO] [*.sub.mycomain.com] acme: Waiting for DNS record propagation.
2019/01/23 11:50:45 [INFO] [sub.mycomain.com] The server validated our request
2019/01/23 11:50:46 [INFO] [sub.mycomain.com] acme: Trying to solve DNS-01
2019/01/23 11:50:46 [INFO] [sub.mycomain.com] acme: Checking DNS record propagation using [a1-216.akam.net:53]
2019/01/23 11:50:46 [INFO] Wait for propagation [timeout: 5m0s, interval: 5s]
2019/01/23 11:50:47 [INFO] [sub.mycomain.com] The server validated our request
2019/01/23 11:50:47 [INFO] [*.sub.mycomain.com] acme: Cleaning DNS-01 challenge
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/xenolf/lego/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).removeNonCnameName(0xc0000b8480, 0xc0005ab200, 0x14)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:801 +0x246
github.com/xenolf/lego/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).removeTxtRecord(0xc0000b8480, 0xc0002e0b40, 0xc0002e0b40, 0xc00056e520)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:756 +0x1cb
github.com/xenolf/lego/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1.(*Zone).RemoveRecord(0xc0000b8480, 0xf1e6a0, 0xc0002e0b40, 0x14, 0xc0002e0b40)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/vendor/github.com/akamai/AkamaiOPEN-edgegrid-golang/configdns-v1/zone.go:278 +0x6c6
github.com/xenolf/lego/providers/dns/fastdns.(*DNSProvider).CleanUp(0xc00000e8d0, 0xc0005abda0, 0x13, 0xc0006c8810, 0x2b, 0xc00076a000, 0x57, 0xc000519408, 0x3)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/providers/dns/fastdns/fastdns.go:118 +0x2e6
github.com/xenolf/lego/challenge/dns01.(*Challenge).CleanUp(0xc0003289c0, 0xc000519420, 0x7, 0x0, 0xed3e3783d, 0x0, 0xc000519408, 0x3, 0xc0005abda0, 0x13, ...)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/challenge/dns01/dns_challenge.go:155 +0x2a9
github.com/xenolf/lego/challenge/resolver.cleanUp(0x11d75c0, 0xc0003289c0, 0xc000519420, 0x7, 0x0, 0xed3e3783d, 0x0, 0xc000519408, 0x3, 0xc0005abda0, ...)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/challenge/resolver/prober.go:168 +0x10f
github.com/xenolf/lego/challenge/resolver.parallelSolve.func1(0xc0003e81e0, 0x2, 0x2)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/challenge/resolver/prober.go:145 +0x7e
github.com/xenolf/lego/challenge/resolver.parallelSolve(0xc0003e81e0, 0x2, 0x2, 0xc00028bdd0)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/challenge/resolver/prober.go:163 +0x49b
github.com/xenolf/lego/challenge/resolver.(*Prober).Solve(0xc00000e8c8, 0xc00008e5b0, 0x2, 0x2, 0x1e, 0xc0000a4400)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/challenge/resolver/prober.go:84 +0x35e
github.com/xenolf/lego/certificate.(*Certifier).Obtain(0xc0003762d0, 0xc0002baa40, 0x2, 0x2, 0x1, 0x0, 0x0, 0x0, 0x101, 0xc0008b8c00, ...)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/certificate/certificates.go:114 +0x36e
github.com/xenolf/lego/cmd.obtainCertificate(0xc00009cc60, 0xc000526d40, 0xc00042fa80, 0x1, 0x1)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/cmd/cmd_run.go:151 +0x2a5
github.com/xenolf/lego/cmd.run(0xc00009cc60, 0x0, 0x2)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/cmd/cmd_run.go:76 +0xb4
github.com/xenolf/lego/vendor/github.com/urfave/cli.HandleAction(0xe94700, 0x10cc660, 0xc00009cc60, 0xc000079000, 0x0)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/vendor/github.com/urfave/cli/app.go:490 +0xc8
github.com/xenolf/lego/vendor/github.com/urfave/cli.Command.Run(0x1082538, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10b41f0, 0x3a, 0x0, ...)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/vendor/github.com/urfave/cli/command.go:210 +0x990
github.com/xenolf/lego/vendor/github.com/urfave/cli.(*App).Run(0xc00026da00, 0xc000030100, 0x10, 0x10, 0x0, 0x0)
	/home/mlois/workspace.go/src/github.com/xenolf/lego/vendor/github.com/urfave/cli/app.go:255 +0x687
main.main()
	/home/mlois/workspace.go/src/github.com/xenolf/lego/cmd/lego/main.go:43 +0x19d
```
The DNS record during the challenge:

```bash
dig @a1-216.akam.net TXT _acme-challenge.sub.mycomain.com 
;; ANSWER SECTION:
_acme-challenge.sub.mycomain.com. 120 IN TXT	"ZQSbSIqOXK9oo3BxqUaZ_Ty6w6Sk7UyFi9b1GjVuQ1A"
_acme-challenge.sub.mycomain.com. 120 IN TXT	"DQtiicqDOH-YjguzZZldW53MlUNhzNclM7spodg4ql8"
```
Due to the error the cleanup was not launched and the records were not removed.

Yesterday I launch a make test on the lego project, and a lot of test fails on latest master branch, I launch only the fastdns test, and all runs ok, I use this command: 

```bash
GOCACHE=off go test -v -cover github.com/xenolf/lego/providers/dns/fastdns
```

**Comment by securez** [comment]
Hi, 

Ok, I'll track the PR and Open a case on Akamai, to see if this make things go faster.

A lot of thanks for the effort!!!

**Comment by ldez** [comment]
you can retry with with this branch [fix/fastdns](https://github.com/xenolf/lego/tree/fix/fastdns)

**Comment by securez** [comment]
Ok, I'll send the PR to technical Akamai team, so they can take a look at it. 

I'll test the new version in few minutes.

**Comment by ldez** [comment]
See #774
